# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "QRCode Generator"
client_id = "e1d10b1346ff137709bd2c42e442060e"
application_url = "https://sorted-iraqi-provincial-accommodations.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sorted-iraqi-provincial-accommodations.trycloudflare.com/auth/callback",
  "https://sorted-iraqi-provincial-accommodations.trycloudflare.com/auth/shopify/callback",
  "https://sorted-iraqi-provincial-accommodations.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-7998b600.myshopify.com"
